---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build gatsby
  image: alpine:latest
  commands:
  - cd dev.simonemessaggi.it && node -v
  - ls -la
  - npm ci
  - mv static/robots.prod static/robots.txt
  - npm run build
