---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build gatsby
  image: alpine:latest
  commands:
  - sh ' cd dev.simonemessaggi.it && node -v'
  - sh 'ls -la'
  - sh 'npm ci'
  - sh 'mv static/robots.prod static/robots.txt'
  - sh 'npm run build'
